<?php

namespace api\controllers;

use api\transformers\BannerList;
use api\transformers\CityList;
use common\models\Banner;
use common\models\City;
use yii\web\Controller;

class BannerController extends Controller
{

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionList()
    {
        $banners = Banner::find()->where(['status' => 1, 'type' => 1])->andWhere(['>', 'expires_in', time()])->orderBy('order')->limit(5)->all();

        return $this->asJson(['data' => BannerList::transform($banners)]);
    }
}
