<?php

namespace api\controllers;

use Yii;
use yii\web\Controller;

class BoostController extends Controller
{

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionList()
    {
        $names = [
            'colored_offer' => Yii::t('frontend', 'Colored offer'),
            'special_offer' => Yii::t('frontend', 'Special offer'),
        ];
        $prices = [];

        if (isset(Yii::$app->params['boost_price'])){
            foreach (Yii::$app->params['boost_price'] as $type => $data) {
                $prices[] = [
                    'type' => $type,
                    'name' => $names[$type],
                    'duration_days' => $data['days'],
                    'price' => $data['price'],
                ];
            }
        }
        return $this->asJson(['data' => $prices]);
    }
}
