<?php

namespace api\controllers;

use api\transformers\AnnounceList;
use api\transformers\BrandsList;
use api\transformers\CategoryList;
use api\transformers\LineupList;
use api\transformers\MetaData;
use api\transformers\OptionList;
use common\models\Brand;
use common\models\Category;
use common\models\Lineup;
use common\models\OptionGroup;
use common\models\OptionValue;
use common\models\Product;
use common\models\Shop;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;

class CategoryController extends Controller
{
    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionAnnouncements($id)
    {
        $data = $this->getDataByID($id, 'announcements');
        if (isset($data['message'])) {
            return $this->redirect(['site/error', 'message' => $data['message'], 'code' => $data['code']]);
        }


        return $this->asJson([
            'data' => AnnounceList::transform($data['announcements'], $data['currency']),
            'meta' => MetaData::transform($data['pagination']),
        ]);
    }

    public function actionBrands($id)
    {
        $data = $this->getDataByID($id, 'brands');
        if (isset($data['message'])) {
            return $this->redirect(['site/error', 'message' => $data['message'], 'code' => $data['code']]);
        }

        return $this->asJson([
            'data' => BrandsList::transform($data['brands']),
        ]);
    }

    public function actionLineups($id)
    {
        $data = $this->getDataByID($id, 'lineups');
        if (isset($data['message'])) {
            return $this->redirect(['site/error', 'message' => $data['message'], 'code' => $data['code']]);
        }

        return $this->asJson([
            'data' => LineupList::transform($data['lineups']),
        ]);
    }

    public function actionOptions($id)
    {
        $data = $this->getDataByID($id, 'options');
        if (isset($data['message'])) {
            return $this->redirect(['site/error', 'message' => $data['message'], 'code' => $data['code']]);
        }

        return $this->asJson([
            'data' => OptionList::transform($data['options'], $id),
            'meta' => $data['meta'],
        ]);
    }

    public function actionList($id = null)
    {
        $category = null;
        if ($id) {
            $category = Category::find()->where(['status' => 1, 'id' => $id])->orderBy('order')->all();
        } else {
            $category = Category::find()->where(['status' => 1, 'parent_id' => null])->orderBy('order')->all();
        }
        if ($category) {
            return $this->asJson(['data' => CategoryList::transform($category)]);
        } else {
            return $this->redirect(['site/error', 'message' => 'Not Found', 'code' => 404]);
        }
    }

    public function getDataByID($id, $return)
    {
        $category = Category::findOne(['status' => 1, 'id' => $id]);
        if (empty($category)) return ['message' => 'Not Found', 'code' => 404];
//        if ($category->on_main == 1) return ['message' => 'Not Found', 'code' => 404];

        $unset = false;
        $temp_parent = $category;
        while ($temp_parent) {
            if (!$temp_parent->status) {
                $unset = true;
                break;
            }
            if (empty($temp_parent->parent)) break;
            $temp_parent = $temp_parent->parent;
        }

        $city_id = Yii::$app->request->get('city_id', false);

        $type = Yii::$app->request->get('type', null);
        $dealer_id = Yii::$app->request->get('dealer', null);

        $special = Yii::$app->request->get('special', null);
        $brands_passed = Yii::$app->request->get('brands', []);
        if(is_array($brands_passed)) {
            $brands_passed = array_filter($brands_passed);
        }
        $lineups_passed = Yii::$app->request->get('lineups', []);
        if(is_array($lineups_passed)) {
            $lineups_passed = array_filter($lineups_passed);
        }

//        $category_views = (!empty(Yii::$app->session->get('category_views')))? Yii::$app->session->get('category_views'): [];
//        if(!in_array($temp_parent->id, $category_views)) {
//            $category_views[] = $temp_parent->id;
//            Yii::$app->session->set('category_views', $category_views);
            $temp_parent->view++;
            $temp_parent->save();
//        }

        if ($unset) return ['message' => 'Not Found', 'code' => 404];
        $photo = Yii::$app->request->get('photo', 0);
        $q = Yii::$app->request->get('q', null);
        $currency = Yii::$app->request->get('currency', 'uzs');
        $cat_ids = $this->get_ids($category) . $category->id;
        $products = false;
        $special_products = false;
        if (!empty($cat_ids)) {
            $sort['s'] = '`created_at`';
            $sort['sd'] = 'desc';
//            if (Yii::$app->request->get('s') == 'p') $sort['s'] = '`special_offer`';
            if (Yii::$app->request->get('s') == 'p') $sort['s'] = '`price`';
            if (Yii::$app->request->get('s') == 'd') $sort['s'] = '`created_at`';
//            if (Yii::$app->request->get('sd') == 'a') $sort['sd'] = 'desc';
            if (Yii::$app->request->get('sd') == 'a') $sort['sd'] = 'asc';

            if ($type == 'sell' || $type == 'buy' || $type == 'arenda') {
                $products = Product::find()->where(['status' => 1, 'type' => $type]);
            } else {
                $products = Product::find()->where(['status' => 1]);
            }
            if ($special == 1) {
                $products->andWhere(['>', 'special_offer', time()]);
            } else {
                $query = clone $products;
                $special_products = $query->andWhere(['>', 'special_offer', time()])
                    ->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])
                    ->orderBy($sort['s'] . " " . $sort['sd'])
                    ->all();
            }
            if($dealer_id) {
                $products->andWhere(['shop_id' => $dealer_id]);
            }

            $products = $products->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])
//                ->orderBy("`special_offer` DESC")
//                    ->andWhere(['<', 'special_offer', time()])
                ->orderBy($sort['s'] . " " . $sort['sd'])
                ->all();
        }
        $shops = [];
        $brands = [];
        $lineups = [];
        $brands_count = [];
        $lineups_count = [];
        $options = [];
        $filtered_products = $products;
        if ($currency == 'usd') {
            $def_pStart = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('price_usd') ?
                Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('price_usd') : 0;
            $def_pEnd = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('price_usd') ?
                Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('price_usd') : 0;
        } else {
            $def_pStart = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('price') ?
                Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('price') : 0;
            $def_pEnd = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('price') ?
                Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('price') : 0;
        }

        $def_kmStart = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('km') ?
            Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('km') : 0;
        $def_kmEnd = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('km') ?
            Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('km') : 0;

        $price_range = Yii::$app->request->get('price_range') != '' ? Yii::$app->request->get('price_range') : '';
        $price_range = explode(';', $price_range);
        $pStart = isset($price_range[0]) ? $price_range[0] : $def_pStart;
        $pEnd = isset($price_range[1]) ? $price_range[1] : $def_pEnd;

        $kmStart = Yii::$app->request->get('kmstart') != '' ? Yii::$app->request->get('kmstart') : $def_kmStart;
        $kmEnd = Yii::$app->request->get('kmend') != '' ? Yii::$app->request->get('kmend') : $def_kmEnd;


        $filters = array();
        if (!empty(Yii::$app->request->get('filters'))) {
            for ($i = 0; $i < count(Yii::$app->request->get('filters')); $i++) {
                $temp_filter = explode('_', Yii::$app->request->get('filters')[$i]);
                if (count($temp_filter) != 2) continue;
                $filters[$temp_filter[0]][] = $temp_filter[1];
            }
        }
        $delete = array();
        if (!empty($products)) {
            for ($i = 0; $i < count($products); $i++) {
                if ($products[$i]->brand_id) {
                    if (empty($brands[$products[$i]->brand_id])) {
                        $brands[$products[$i]->brand_id] = Brand::findOne(['id' => $products[$i]->brand_id, 'status' => 1]);
                    }
                }
                if ($products[$i]->lineup_id) {
                    if (!empty($brands_passed)) {
                        if (in_array($products[$i]->brand_id, $brands_passed)) {
                            if (empty($lineups[$products[$i]->lineup_id])) {
                                $lineups[$products[$i]->lineup_id] = Lineup::findOne(['id' => $products[$i]->lineup_id, 'status' => 1]);
                            }
                        }
                    } else {
                        if (empty($lineups[$products[$i]->lineup_id])) {
                            $lineups[$products[$i]->lineup_id] = Lineup::findOne(['id' => $products[$i]->lineup_id, 'status' => 1]);
                        }
                    }
                }

                if ($currency == 'usd') {
                    $products[$i]->price = $products[$i]->price_usd;
                    $products[$i]->wholesale = $products[$i]->wholesale_usd;
                }
                if ($products[$i]->shop_id && $products[$i]->shop->status != 1) {
                    if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                    continue;
                }
                if ($products[$i]->user_id && $products[$i]->user->status != 10) {
                    if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                    continue;
                }
                $opt_ids = array();
                if (!empty($filters)) $delete = array();
                for ($k = 0; $k < count($products[$i]->activeOptions); $k++) {
                    $opt = OptionValue::findOne(['id' => $products[$i]->activeOptions[$k]->option_id, 'status' => 1]);
                    $opt_ids[] = $opt->id;
                    if (empty($options['group'][$opt->group_id])) $options['group'][$opt->group_id] = OptionGroup::findOne(['id' => $opt->group_id, 'status' => 1]);
                    if (empty($options['values'][$opt->group_id][$opt->id])) $options['values'][$opt->group_id][$opt->id] = $opt;
                }
                if (empty($shops[$products[$i]->shop_id])) $shops[$products[$i]->shop_id] = Shop::findOne(['id' => $products[$i]->shop_id, 'status' => 1]);
                if (!empty($filters)) {
                    foreach ($filters as $key => $v) {
                        if (!empty($opt_ids)) {
                            for ($of = 0; $of < count($opt_ids); $of++) {
                                if (in_array($opt_ids[$of], $v)) {
                                    $delete[$key] = 'yes';
                                    break;
                                } else $delete[$key] = 'no';
                            }
                        } else $delete[$key] = 'no';
                    }
                }
                if ($q && $q != '') {
                    if (mb_strpos($products[$i]->translate->name, $q) === false && mb_strpos($products[$i]->translate->description, $q) === false) if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                }
                if (!empty($filters)) {
                    if (in_array('no', $delete)) if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                }
                if (!empty($brands_passed)) {
                    if (!in_array($products[$i]->brand_id, $brands_passed)) if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                }
                if (!empty($lineups_passed)) {
                    if (!in_array($products[$i]->lineup_id, $lineups_passed)) if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                }

                if ($photo) {
                    if ($products[$i]->mainImage->image == '/uploads/site/default_product.png') {
                        if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                    }
                }

                if (($products[$i]->sale->value > 0)) {
                    if ($products[$i]->sale->type == 0) {
                        $prod_price = $products[$i]->price - ($products[$i]->price * $products[$i]->sale->value);
                    } else {
                        $prod_price = $products[$i]->price - $products[$i]->sale->value;
                    }
                } else {
                    $prod_price = $products[$i]->price;
                }

                if ($prod_price < $def_pStart) $def_pStart = $prod_price;
                $pStart = Yii::$app->request->get('price_range') != '' ? $pStart : $def_pStart;
                if (!(($pStart <= $prod_price) && ($prod_price <= $pEnd))) if (isset($filtered_products[$i])) unset($filtered_products[$i]);

                $kmStart = Yii::$app->request->get('kmstart') != '' ? $kmStart : $def_kmStart;
                if ($products[$i]->km < $def_kmStart) $def_kmStart = $products[$i]->km;
                if (!(($kmStart <= $products[$i]->km) && ($products[$i]->km <= $kmEnd))) if (isset($filtered_products[$i])) unset($filtered_products[$i]);


                if ($city_id && $products[$i]->shop_id) {
                    if (!in_array($city_id, (json_decode($products[$i]->shop->cities)) ? json_decode($products[$i]->shop->cities) : [])) {
                        if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                        continue;
                    }
                } else if ($city_id && $products[$i]->user_id) {
                    if ($products[$i]->user->city_id != $city_id) {
                        if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                        continue;
                    }
                }
            }
        }

        $filtered_products_simple = [];
        $filtered_products_spec = [];
        $filter_options = [];
        foreach ($filtered_products as $product_loop) {

            for ($k = 0; $k < count($product_loop->activeOptions); $k++) {
                $fil_opt = OptionValue::findOne(['id' => $product_loop->activeOptions[$k]->option_id, 'status' => 1]);
                if (empty($filter_options['group'][$fil_opt->group_id])) $filter_options['group'][$fil_opt->group_id] = OptionGroup::findOne(['id' => $fil_opt->group_id, 'status' => 1]);
                if (empty($filter_options['values'][$fil_opt->group_id][$fil_opt->id])) $filter_options['values'][$fil_opt->group_id][$fil_opt->id] = $fil_opt;
            }
            if ($product_loop->brand_id) {
                if(isset($brands_count[$product_loop->brand_id])) {
                    $brands_count[$product_loop->brand_id] += 1;
                } else {
                    $brands_count[$product_loop->brand_id] = 1;
                }
            }
            if ($product_loop->lineup_id) {

                if (!empty($brands_passed)) {
                    if (in_array($product_loop->brand_id, $brands_passed)) {
                        if(isset($lineups_count[$product_loop->lineup_id])) {
                            $lineups_count[$product_loop->lineup_id] += 1;
                        } else {
                            $lineups_count[$product_loop->lineup_id] = 1;
                        }
                    }
                } else {
                    if(isset($lineups_count[$product_loop->lineup_id])) {
                        $lineups_count[$product_loop->lineup_id] += 1;
                    } else {
                        $lineups_count[$product_loop->lineup_id] = 1;
                    }
                }
            }


            if($product_loop->special_offer > time()) {
                $filtered_products_spec[] = $product_loop;
            } else {
                $filtered_products_simple[] = $product_loop;
            }
        }


        if (!empty($filtered_products_spec)) {
            usort($filtered_products_spec, function ($a, $b) {
                if ($a->special_offer == $b->special_offer) {
                    return 0;
                }
                return ($a->special_offer < $b->special_offer) ? 1 : -1;
            });
        }

        $ordered_products = [];
        $it = 0;
        $spec_it = 0;

        if(empty($filtered_products_simple)) {
            $ordered_products = $filtered_products_spec;
        } else {
            foreach ($filtered_products_simple as $fps) {
                $fpc_cnt = $spec_it;
                if(($it % 7) === 0) {
                    for($fpc_it = $fpc_cnt; $fpc_it < $fpc_cnt + 3; $fpc_it++) {
                        if(isset($filtered_products_spec[$fpc_it])) {
                            $ordered_products[] = $filtered_products_spec[$fpc_it];
                        }
                        $spec_it++;
                    }
                }
                $ordered_products[] = $fps;
                $it++;
                if($it == count($filtered_products_simple)) {
                    for($fpc_it = $spec_it; $fpc_it < count($filtered_products_spec); $fpc_it++) {
                        if(isset($filtered_products_spec[$fpc_it])) {
                            $ordered_products[] = $filtered_products_spec[$fpc_it];
                        }
                    }
                }
            }
        }
        $filtered_products = $ordered_products;

        $page_count = ceil(count(array_values($filtered_products)) / Yii::$app->params['pageSize']);
        if (Yii::$app->request->get('page') > $page_count) {
            return ['message' => 'Not Found', 'code' => 404];
        }
        $page_offset = !empty(Yii::$app->request->get('page')) ? ((Yii::$app->request->get('page') - 1) * Yii::$app->params['pageSize']) : 0;
        if ($page_offset < 0) return ['message' => 'Not Found', 'code' => 404];
        $filtered_products_slice = array_slice(array_values($filtered_products), $page_offset, Yii::$app->params['pageSize']);

        if (!empty($filter_options['values'])) {
            foreach ($filter_options['values'] as $group_id => $sort_opt) {
                usort($filter_options['values'][$group_id], function ($a, $b) {
                    if (is_numeric($a->translate->name)) {
                        if ($a->translate->name == $b->translate->name) {
                            return 0;
                        }
                        return ($a->translate->name < $b->translate->name) ? 1 : -1;
                    }
                    return 1;
                });
            }
        }

        if ($return == 'announcements') {
            return [
                'announcements' => array_values($filtered_products_slice),
                'pagination' => new Pagination(['totalCount' => count(array_values($filtered_products)), 'pageSize' => Yii::$app->params['pageSize']]),
                'currency' => $currency,
            ];
        }
        if ($return == 'brands') {
            return [
                'brands' => $brands,
            ];
        }
        if ($return == 'options') {
            return [
                'options' => $filter_options,
                'meta' => [
                    'price_from' => $def_pStart,
                    'price_to' => $def_pEnd,
                    'mileage_from' => $def_kmStart,
                    'mileage_to' => $def_kmEnd,
                ],
            ];
        }

        if ($return == 'lineups') {
            if (!empty($brands_passed)) {
                return [
                    'lineups' => $lineups,
                ];
            }
            return [
                'lineups' => [],
            ];
        }

//        return $this->render('index', [
//            'photo' => $photo,
//            'pStart' => $pStart,
//            'pEnd' => $pEnd,
//            'kmStart' => $kmStart,
//            'kmEnd' => $kmEnd,

//            'brands_count' => $brands_count,
//            'lineups_count' => $lineups_count,

//            'special_products' => $special_products,
//        ]);
    }

    protected function get_ids($category)
    {
        $sub = false;
        for ($s = 0; $s < count($category->activeCategories); $s++) {
            if ($category->activeCategories[$s]) {
                $sub .= $category->activeCategories[$s]->id . ",";
            }
            $sub .= $this->get_ids($category->activeCategories[$s]);
        }
        return $sub;
    }

}
