<?php

namespace api\controllers;

use api\transformers\BrandsList;
use api\transformers\DealerList;
use api\transformers\LineupList;
use api\transformers\MetaData;
use api\transformers\OptionList;
use common\models\Brand;
use common\models\Category;
use common\models\Lineup;
use common\models\OptionGroup;
use common\models\OptionValue;
use common\models\Product;
use common\models\Shop;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;

class DealerController extends Controller
{
    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionShowNumber()
    {
        $id = !empty(Yii::$app->request->get('id'))? Yii::$app->request->get('id'): false;
        if(!$id) {
            return $this->asJson(['phones' => null]);
        }
        $shop = Shop::findOne($id);
        if(empty($shop)) {
            return $this->asJson(['phones' => null]);
        }
        $shop->info->phone = explode('; ', $shop->info->phone);

        if($shop->info->phone != '') {
//            $shop_phones = (!empty(Yii::$app->session->get('shop_phones')))? Yii::$app->session->get('shop_phones'): [];
//            if(!in_array($shop->id, $shop_phones)) {
//                $shop_phones[] = $shop->id;
//                Yii::$app->session->set('shop_phones', $shop_phones);
                $shop->view_phone++;
                $shop->save();
//            }
            return $this->asJson(['phones' => $shop->info->phone]);
        }

        return $this->asJson(['phones' => null]);
    }

    public function getIndexById($id)
    {
        $shop = Shop::findOne(['status' => 1, 'id' => $id]);
        if (empty($shop)) return ['message' => 'Not Found', 'code' => 404];

//        $shop_views = (!empty(Yii::$app->session->get('shop_views')))? Yii::$app->session->get('shop_views'): [];
//        if(!in_array($shop->id, $shop_views)) {
//            $shop_views[] = $shop->id;
//            Yii::$app->session->set('shop_views', $shop_views);
            $shop->view++;
            $shop->save();
//        }
        return [
            'dealer' => $shop
        ];
    }

    public function actionShow($id)
    {
        $data = $this->getIndexById($id);
        if (isset($data['message'])) {
            return $this->redirect(['site/error', 'message' => $data['message'], 'code' => $data['code']]);
        }

        return $this->asJson([
            'data' => DealerList::transform([$data['dealer']]),
        ]);
    }



    public function actionList($id)
    {
        $data = $this->getListById($id);
        if (isset($data['message'])) {
            return $this->redirect(['site/error', 'message' => $data['message'], 'code' => $data['code']]);
        }

        return $this->asJson([
            'data' => DealerList::transform($data['dealers'], $data['dealers_announce_count']),
            'meta' => MetaData::transform($data['pagination']),
        ]);
    }

//    public function actionBrands($id)
//    {
//        $data = $this->getListById($id, 'brands');
//        if (isset($data['message'])) {
//            return $this->redirect(['site/error', 'message' => $data['message'], 'code' => $data['code']]);
//        }
//
//        return $this->asJson([
//            'data' => BrandsList::transform($data['brands']),
//        ]);
//    }
//
//    public function actionLineups($id)
//    {
//        $data = $this->getListById($id, 'lineups');
//        if (isset($data['message'])) {
//            return $this->redirect(['site/error', 'message' => $data['message'], 'code' => $data['code']]);
//        }
//
//        return $this->asJson([
//            'data' => LineupList::transform($data['lineups']),
//        ]);
//    }
//
//    public function actionOptions($id)
//    {
//        $data = $this->getListById($id, 'options');
//        if (isset($data['message'])) {
//            return $this->redirect(['site/error', 'message' => $data['message'], 'code' => $data['code']]);
//        }
//
//        return $this->asJson([
//            'data' => OptionList::transform($data['options'], $id),
//            'meta' => $data['meta'],
//        ]);
//    }

    public function getListById($id)
    {
        $category = Category::findOne(['status' => 1, 'id' => $id]);
        if (empty($category)) return ['message' => 'Not Found', 'code' => 404];
        if ($category->on_main == 1) return ['message' => 'Not Found', 'code' => 404];

        $unset = false;
        $temp_parent = $category;
        while($temp_parent){
            if (!$temp_parent->status) {
                $unset = true;
                break;
            }
            if(empty($temp_parent->parent)) break;
            $temp_parent = $temp_parent->parent;
        }

        $city_id = Yii::$app->request->get('city_id', false);

        $brands_passed = Yii::$app->request->get('brands', []);
        if(is_array($brands_passed)) {
            $brands_passed = array_filter($brands_passed);
        }

        $lineups_passed = Yii::$app->request->get('lineups', []);
        if(is_array($lineups_passed)) {
            $lineups_passed = array_filter($lineups_passed);
        }

//        $category_views = (!empty(Yii::$app->session->get('category_views')))? Yii::$app->session->get('category_views'): [];
//        if(!in_array($temp_parent->id, $category_views)) {
//            $category_views[] = $temp_parent->id;
//            Yii::$app->session->set('category_views', $category_views);
        $temp_parent->view++;
        $temp_parent->save();
//        }

        if($unset) return ['message' => 'Not Found', 'code' => 404];
        $photo = Yii::$app->request->get('photo', 0);
        $currency = Yii::$app->request->get('currency', 'uzs');



        $cat_ids = $this->get_ids($category) . $category->id;
        $products = false;
        if (!empty($cat_ids)) {
            $sort['s'] = '`view`';
            $sort['sd'] = 'desc';
            if (Yii::$app->request->get('s') == 'p') $sort['s'] = '`price`';
            if (Yii::$app->request->get('s') == 'd') $sort['s'] = '`created_at`';
            if (Yii::$app->request->get('sd') == 'a') $sort['sd'] = 'asc';
            $products = Product::find()->where(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->orderBy($sort['s'] . " " . $sort['sd'])->all();
        }
        $shops = [];
        $shops_products = [];
        $brands = [];
        $lineups = [];
        $brands_count = [];
        $lineups_count = [];
        $options = [];
        $filtered_products = $products;

        if($currency == 'usd') {
            $def_pStart = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('price_usd') ?
                Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('price_usd') : 0;
            $def_pEnd = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('price_usd') ?
                Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('price_usd') : 0;
        } else {
            $def_pStart = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('price') ?
                Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('price') : 0;
            $def_pEnd = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('price') ?
                Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('price') : 0;
        }
        $def_kmStart = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('km') ?
            Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->min('km') : 0;
        $def_kmEnd = Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('km') ?
            Product::find()->andWhere(['status' => 1])->andWhere(['or', '`category_id` IN (' . $cat_ids . ')', '`add_cats` LIKE "%,' . $category->id . ',%"'])->max('km') : 0;

        $price_range = Yii::$app->request->get('price_range') != '' ? Yii::$app->request->get('price_range') : '';
        $price_range = explode(';', $price_range);
        $pStart = isset($price_range[0])? $price_range[0]: $def_pStart;
        $pEnd = isset($price_range[1])? $price_range[1]: $def_pEnd;

        $kmStart = Yii::$app->request->get('kmstart') != '' ? Yii::$app->request->get('kmstart') : $def_kmStart;
        $kmEnd = Yii::$app->request->get('kmend') != '' ? Yii::$app->request->get('kmend') : $def_kmEnd;


        $filters = array();
        if (!empty(Yii::$app->request->get('filters'))) {
            for ($i = 0; $i < count(Yii::$app->request->get('filters')); $i++) {
                $temp_filter = explode('_', Yii::$app->request->get('filters')[$i]);
                if (count($temp_filter) != 2) continue;
                $filters[$temp_filter[0]][] = $temp_filter[1];
            }
        }
        $delete = array();
        if (!empty($products)) {
            for ($i = 0; $i < count($products); $i++) {
                if ($products[$i]->brand_id) {
                    if (empty($brands[$products[$i]->brand_id])) {
                        $brands[$products[$i]->brand_id] = Brand::findOne(['id' => $products[$i]->brand_id, 'status' => 1]);
                    }
                }
                if ($products[$i]->lineup_id) {
                    if (!empty($brands_passed)) {
                        if (in_array($products[$i]->brand_id, $brands_passed)) {
                            if (empty($lineups[$products[$i]->lineup_id])) {
                                $lineups[$products[$i]->lineup_id] = Lineup::findOne(['id' => $products[$i]->lineup_id, 'status' => 1]);
                            }
                        }
                    } else {
                        if (empty($lineups[$products[$i]->lineup_id])) {
                            $lineups[$products[$i]->lineup_id] = Lineup::findOne(['id' => $products[$i]->lineup_id, 'status' => 1]);
                        }
                    }
                }

                if($currency == 'usd') {
                    $products[$i]->price = $products[$i]->price_usd;
                    $products[$i]->wholesale = $products[$i]->wholesale_usd;
                }
                if ($products[$i]->shop_id && $products[$i]->shop->status != 1) {
                    if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                    continue;
                }
                if ($products[$i]->user_id && $products[$i]->user->status != 10) {
                    if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                    continue;
                }
                $opt_ids = array();
                if (!empty($filters)) $delete = array();
                for ($k = 0; $k < count($products[$i]->activeOptions); $k++) {
                    $opt = OptionValue::findOne(['id' => $products[$i]->activeOptions[$k]->option_id, 'status' => 1]);
                    $opt_ids[] = $opt->id;
                    if (empty($options['group'][$opt->group_id])) $options['group'][$opt->group_id] = OptionGroup::findOne(['id' => $opt->group_id, 'status' => 1]);
                    if (empty($options['values'][$opt->group_id][$opt->id])) $options['values'][$opt->group_id][$opt->id] = $opt;
                }

                if (!empty($filters)) {
                    foreach ($filters as $key => $v) {
                        if (!empty($opt_ids)) {
                            for ($of = 0; $of < count($opt_ids); $of++) {
                                if (in_array($opt_ids[$of], $v)) {
                                    $delete[$key] = 'yes';
                                    break;
                                } else $delete[$key] = 'no';
                            }
                        } else $delete[$key] = 'no';
                    }
                }
                if (!empty($filters)) {
                    if (in_array('no', $delete)) if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                }
                if (!empty($brands_passed)) {
                    if (!in_array($products[$i]->brand_id, $brands_passed)) if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                }
                if (!empty($lineups_passed)) {
                    if (!in_array($products[$i]->lineup_id, $lineups_passed)) if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                }

                if ($photo) {
                    if ($products[$i]->mainImage->image == '/uploads/site/default_product.png') {
                        if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                    }
                }
                if(($products[$i]->sale->value > 0)) {
                    if($products[$i]->sale->type == 0){
                        $prod_price = $products[$i]->price - ($products[$i]->price * $products[$i]->sale->value);
                    }
                    else {
                        $prod_price = $products[$i]->price - $products[$i]->sale->value;
                    }
                }
                else {
                    $prod_price = $products[$i]->price;
                }

                if($prod_price < $def_pStart) $def_pStart = $prod_price;
                $pStart = Yii::$app->request->get('price_range') != '' ? $pStart : $def_pStart;
                if (!(($pStart <= $prod_price) && ($prod_price <= $pEnd))) if (isset($filtered_products[$i])) unset($filtered_products[$i]);

                $kmStart = Yii::$app->request->get('kmstart') != '' ? $kmStart : $def_kmStart;
                if($products[$i]->km < $def_kmStart) $def_kmStart = $products[$i]->km;
                if (!(($kmStart <= $products[$i]->km) && ($products[$i]->km <= $kmEnd))) if (isset($filtered_products[$i])) unset($filtered_products[$i]);


                if($city_id && $products[$i]->shop_id) {
                    if(!in_array($city_id, (json_decode($products[$i]->shop->cities))? json_decode($products[$i]->shop->cities): [])) {
                        if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                        continue;
                    }
                } else if($city_id && $products[$i]->user_id) {
                    if($products[$i]->user->city_id != $city_id) {
                        if (isset($filtered_products[$i])) unset($filtered_products[$i]);
                        continue;
                    }
                }
            }
        }

        foreach ($filtered_products as $product) {
            if($product->shop_id) {
                if (empty($shops[$product->shop_id]))
                {
                    $shops[$product->shop_id] = Shop::findOne(['id' => $product->shop_id, 'status' => 1]);
                }

                if(isset($shops_products[$product->shop_id])) {
                    $shops_products[$product->shop_id] += 1;
                } else {
                    $shops_products[$product->shop_id] = 1;
                }
            }
        }

        $filter_options = [];
        foreach ($filtered_products as $product_loop) {

            for ($k = 0; $k < count($product_loop->activeOptions); $k++) {
                $fil_opt = OptionValue::findOne(['id' => $product_loop->activeOptions[$k]->option_id, 'status' => 1]);
                if (empty($filter_options['group'][$fil_opt->group_id])) $filter_options['group'][$fil_opt->group_id] = OptionGroup::findOne(['id' => $fil_opt->group_id, 'status' => 1]);
                if (empty($filter_options['values'][$fil_opt->group_id][$fil_opt->id])) $filter_options['values'][$fil_opt->group_id][$fil_opt->id] = $fil_opt;
            }

            if ($product_loop->brand_id) {
                if(isset($brands_count[$product_loop->brand_id])) {
                    $brands_count[$product_loop->brand_id] += 1;
                } else {
                    $brands_count[$product_loop->brand_id] = 1;
                }
            }
            if ($product_loop->lineup_id) {

                if (!empty($brands_passed)) {
                    if (in_array($product_loop->brand_id, $brands_passed)) {
                        if(isset($lineups_count[$product_loop->lineup_id])) {
                            $lineups_count[$product_loop->lineup_id] += 1;
                        } else {
                            $lineups_count[$product_loop->lineup_id] = 1;
                        }
                    }
                } else {
                    if(isset($lineups_count[$product_loop->lineup_id])) {
                        $lineups_count[$product_loop->lineup_id] += 1;
                    } else {
                        $lineups_count[$product_loop->lineup_id] = 1;
                    }
                }
            }
        }


        $page_count = ceil(count(array_values($shops)) / Yii::$app->params['pageSize']);
        if (Yii::$app->request->get('page') > $page_count) {
            return ['message' => 'Not Found', 'code' => 404];
        }
        $page_offset = !empty(Yii::$app->request->get('page')) ? ((Yii::$app->request->get('page') - 1) * Yii::$app->params['pageSize']) : 0;
        if ($page_offset < 0) return ['message' => 'Not Found', 'code' => 404];
        $filtered_shops = array_slice(array_values($shops), $page_offset, Yii::$app->params['pageSize']);


        if (!empty($filter_options['values'])) {
            foreach ($filter_options['values'] as $group_id =>  $sort_opt) {
                usort($filter_options['values'][$group_id], function ($a, $b){
                    if(is_numeric($a->translate->name)) {
                        if ($a->translate->name == $b->translate->name) {
                            return 0;
                        }
                        return ($a->translate->name < $b->translate->name) ? 1 : -1;
                    }
                    return 1;
                });
            }
        }

        return [
            'dealers' => array_values($filtered_shops),
            'pagination' => new Pagination(['totalCount' => count(array_values($shops)), 'pageSize' => Yii::$app->params['pageSize']]),
            'currency' => $currency,
            'dealers_announce_count' => $shops_products,
        ];
    }

    protected function get_ids($category)
    {
        $sub = false;
        for ($s = 0; $s < count($category->activeCategories); $s++) {
            if ($category->activeCategories[$s]) {
                $sub .= $category->activeCategories[$s]->id . ",";
            }
            $sub .= $this->get_ids($category->activeCategories[$s]);
        }
        return $sub;
    }
}
