<?php

namespace api\controllers;

use api\transformers\MetaData;
use api\transformers\NewsList;
use common\models\News;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;

class NewsController extends Controller
{

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionList()
    {
        $query = News::find()->where(['status' => 1])->orderBy('`created_at` DESC');
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 12]);
        $pages->validatePage = false;
        $news = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->asJson([
            'data' => NewsList::transform($news),
            'meta' => MetaData::transform($pages),
        ]);

    }

    public function actionIndex($id)
    {
        $news = News::findOne(['status' => 1, 'id' => $id]);
        if (empty($news)) $this->redirect(['site/error', 'message' => 'Not Found', 'code' => 404]);

        return $this->asJson([
            'data' => NewsList::transform([$news]),
        ]);
    }
}
